triggers:
- envs: []
  last_enabled_at: null
  name: all_news_article
  pipeline_uuid: all_news_article_pipeline_to_gcs
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-16 08:00:00
  status: inactive
  variables: {}
